# Generated by Django 3.2.3 on 2022-02-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_id',
        ),
    ]
